version: '3.1'

services:

  mysql:
    image: mariadb:10
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: mysql
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: database
      MYSQL_ROOT_PASSWORD: root

  adminer:
    image: adminer
    ports:
      - 8080:8080